spring.application.name=PoductManagementBackend

spring.application.name=springboot-jpa-demo

# JPA Connection Package
spring.datasource.url=jdbc:mysql://localhost:3306/produt_management
spring.datasource.username=root
spring.datasource.password=vedant@555

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
