spring.application.name=LearningRestAPIs

spring.datasource.url=jdbc:postgresql://localhost:5432/studentsDB
spring.datasource.username=postgres
spring.datasource.password=vedant@555

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
